name: Testing libstc42

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Criterion
      run: sudo apt-get install libcriterion-dev
    - name: make
      run: make
    - name: Running tests
      run: ./test.out
